src/Entity/Systems.php
<?php

namespace App\Entity;

use App\Repository\SystemsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SystemsRepository::class)]
class Systems
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $system_id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $token = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $refresh_token = null;

    #[ORM\ManyToOne(inversedBy: 'systems')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $fk_user = null;

    /**
     * @var Collection<int, Energy>
     */
    #[ORM\OneToMany(targetEntity: Energy::class, mappedBy: 'fk_system', orphanRemoval: true)]
    private Collection $energies;

    /**
     * @var Collection<int, Months>
     */
    #[ORM\OneToMany(targetEntity: Months::class, mappedBy: 'fk_system', orphanRemoval: true)]
    private Collection $months;

    public function __construct()
    {
        $this->energies = new ArrayCollection();
        $this->months = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSystemId(): ?string
    {
        return $this->system_id;
    }

    public function setSystemId(?string $system_id): static
    {
        $this->system_id = $system_id;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getRefreshToken(): ?string
    {
        return $this->refresh_token;
    }

    public function setRefreshToken(?string $refresh_token): static
    {
        $this->refresh_token = $refresh_token;

        return $this;
    }

    public function getFkUser(): ?Users
    {
        return $this->fk_user;
    }

    public function setFkUser(?Users $fk_user): static
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    /**
     * @return Collection<int, Energy>
     */
    public function getEnergies(): Collection
    {
        return $this->energies;
    }

    public function addEnergy(Energy $energy): static
    {
        if (!$this->energies->contains($energy)) {
            $this->energies->add($energy);
            $energy->setFkSystem($this);
        }

        return $this;
    }

    public function removeEnergy(Energy $energy): static
    {
        if ($this->energies->removeElement($energy)) {
            // set the owning side to null (unless already changed)
            if ($energy->getFkSystem() === $this) {
                $energy->setFkSystem(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Months>
     */
    public function getMonths(): Collection
    {
        return $this->months;
    }

    public function addMonth(Months $month): static
    {
        if (!$this->months->contains($month)) {
            $this->months->add($month);
            $month->setFkSystem($this);
        }

        return $this;
    }

    public function removeMonth(Months $month): static
    {
        if ($this->months->removeElement($month)) {
            // set the owning side to null (unless already changed)
            if ($month->getFkSystem() === $this) {
                $month->setFkSystem(null);
            }
        }

        return $this;
    }
}

src/Form/SystemsType.php
<?php

namespace App\Form;

use App\Entity\Systems;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SystemsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('system_id')
            ->add('token')
            ->add('refresh_token')
            ->add('fk_user', EntityType::class, [
                'class' => Users::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Systems::class,
        ]);
    }
}

src/Controller/SystemsController.php
<?php

namespace App\Controller;

use App\Entity\Systems;
use App\Form\SystemsType;
use App\Repository\SystemsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/systems')]
class SystemsController extends AbstractController
{
    #[Route('/', name: 'app_systems_index', methods: ['GET'])]
    public function index(SystemsRepository $systemsRepository): Response
    {
        return $this->render('systems/index.html.twig', [
            'systems' => $systemsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_systems_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $system = new Systems();
        $form = $this->createForm(SystemsType::class, $system);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($system);
            $entityManager->flush();

            return $this->redirectToRoute('app_systems_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('systems/new.html.twig', [
            'system' => $system,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_systems_show', methods: ['GET'])]
    public function show(Systems $system): Response
    {
        return $this->render('systems/show.html.twig', [
            'system' => $system,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_systems_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Systems $system, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SystemsType::class, $system);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_systems_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('systems/edit.html.twig', [
            'system' => $system,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_systems_delete', methods: ['POST'])]
    public function delete(Request $request, Systems $system, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$system->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($system);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_systems_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/systems/_delete_form.html.twig
<form method="post" action="{{ path('app_systems_delete', {'id': system.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ system.id) }}">
    <button class="btn">Delete</button>
</form>

templates/systems/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/systems/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Systems{% endblock %}

{% block body %}
    <h1>Edit Systems</h1>

    {{ include('systems/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_systems_index') }}">back to list</a>

    {{ include('systems/_delete_form.html.twig') }}
{% endblock %}

templates/systems/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Systems index{% endblock %}

{% block body %}
    <h1>Systems index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>System_id</th>
                <th>Token</th>
                <th>Refresh_token</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for system in systems %}
            <tr>
                <td>{{ system.id }}</td>
                <td>{{ system.name }}</td>
                <td>{{ system.systemId }}</td>
                <td>{{ system.token }}</td>
                <td>{{ system.refreshToken }}</td>
                <td>
                    <a href="{{ path('app_systems_show', {'id': system.id}) }}">show</a>
                    <a href="{{ path('app_systems_edit', {'id': system.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_systems_new') }}">Create new</a>
{% endblock %}

templates/systems/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Systems{% endblock %}

{% block body %}
    <h1>Create new Systems</h1>

    {{ include('systems/_form.html.twig') }}

    <a href="{{ path('app_systems_index') }}">back to list</a>
{% endblock %}

templates/systems/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Systems{% endblock %}

{% block body %}
    <h1>Systems</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ system.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ system.name }}</td>
            </tr>
            <tr>
                <th>System_id</th>
                <td>{{ system.systemId }}</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>{{ system.token }}</td>
            </tr>
            <tr>
                <th>Refresh_token</th>
                <td>{{ system.refreshToken }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_systems_index') }}">back to list</a>

    <a href="{{ path('app_systems_edit', {'id': system.id}) }}">edit</a>

    {{ include('systems/_delete_form.html.twig') }}
{% endblock %}